### ISSUE TITLE
Adding this to the web middleware breaks other packages

### ISSUE THREAD

**Issue by JamieWBuzz** [erlandmuchasaj/laravel-gzip#1]
Adding `\ErlandMuchasaj\LaravelGzip\Middleware\GzipEncodeResponse::class` to the 'web' middlwareGroup causes packages such a Spatie cookie consent and the laravel debug bar to not display anymore.

**Comment by erlandmuchasaj** [comment]
> Adding `\ErlandMuchasaj\LaravelGzip\Middleware\GzipEncodeResponse::class` to the 'web' middlwareGroup causes packages such a Spatie cookie consent and the laravel debug bar to not display anymore.

Thanks for the info, i will look into it and fix it.

**Comment by Dibbyo456** [comment]
tbh, gzipping responses should only be enabled for production usages (so is debugbar)

**Comment by Pr3d4dor** [comment]
@erlandmuchasaj This is not a middleare priority issue?

I think the gzip middleware need to be always executed as last.

https://laravel.com/docs/11.x/middleware#sorting-middleware

**Comment by erlandmuchasaj** [comment]
> @erlandmuchasaj This is not a middleware priority issue?
> 
> 
> 
> I think the gzip middleware need to be always executed as last.
> 
> 
> 
> https://laravel.com/docs/11.x/middleware#sorting-middleware

It might be, but i will need to debug and investigate further to test it and if needed update the readme doc.

Thanks @Pr3d4dor

**Comment by erlandmuchasaj** [comment]
> Adding `\ErlandMuchasaj\LaravelGzip\Middleware\GzipEncodeResponse::class` to the 'web' middlwareGroup causes packages such a Spatie cookie consent and the laravel debug bar to not display anymore.

Its an ordering issue, you need to place the `GzipEncodeResponse::class` before `CookieConsentMiddleware::class`
