### ISSUE TITLE
gzip on environments other than production

### ISSUE THREAD

**Issue by danikdantist** [erlandmuchasaj/laravel-gzip#7]
Hey there.
Could you please tell me how I can use gzip on environments other than production?

https://github.com/erlandmuchasaj/laravel-gzip/blob/master/src/Middleware/GzipEncodeResponse.php#L25

**Comment by erlandmuchasaj** [comment]
For this use-case @danikdantist  just update you `.env` and put the app in production for testing:

```
APP_ENV=production
APP_DEBUG=false
```

**Comment by fr0z3nfyr** [comment]
Thanks for this wonderful library. It is just sweet.

Sorry for bumping an old issue thread. Just wanted to flag that **this should have been mentioned somewhere in the README as a footnote or something**. I spent an hour trying to figure out what I was doing wrong (my app was in local mode) as the encoding header was not showing up in response!! This particular thread saved me another few hours on a wild goose chase.

Thanks again.
